export { default as QuizzesView } from './QuizzesView.vue'
export { default as CreateView } from './CreateView.vue'
export { default as EditView } from './EditView.vue'
export { default as InviteView } from './InviteView.vue'
export { default as SigninView } from './SigninView.vue'
export { default as SignupView } from './SignupView.vue'
export { default as NotFoundView } from './NotFoundView.vue'